import type { LibraryState, Movie, Shelf } from "./types";

export const defaultShelves: Shelf[] = [
  { id: "horror", name: "Horror", custom: false, order: 0 },
  { id: "comedy", name: "Comedy", custom: false, order: 1 },
  { id: "action", name: "Action", custom: false, order: 2 },
  { id: "sci-fi", name: "Sci-Fi", custom: false, order: 3 },
  { id: "staff-picks", name: "Staff Picks", custom: false, order: 4 },
  { id: "weekend", name: "Weekend Rentals", custom: false, order: 5 },
];

export const sampleMovies: Movie[] = [
  {
    id: "alien",
    title: "Alien",
    year: 1979,
    genres: ["Horror", "Sci-Fi"],
    director: "Ridley Scott",
    runtime: 117,
    coverUrl: "",
    atlasIndex: 0,
    shelfId: "horror",
    notes: "Claustrophobic, patient, and still unmatched.",
    review: "The quiet stretches make every alarm hit harder.",
    rating: 5,
    label: "Cult Classic",
    watchedDates: ["2026-07-05", "2024-10-31"],
    rentalDate: "2026-07-02",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-06-20T14:30:00.000Z",
  },
  {
    id: "back-to-the-future",
    title: "Back to the Future",
    year: 1985,
    genres: ["Comedy", "Sci-Fi"],
    director: "Robert Zemeckis",
    runtime: 116,
    coverUrl: "",
    atlasIndex: 1,
    shelfId: "comedy",
    notes: "Perfect Friday-night rental.",
    review: "Moves like clockwork and never wastes a scene.",
    rating: 5,
    label: "Staff Pick",
    watchedDates: ["2026-06-28"],
    rentalDate: "2026-06-27",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-06-18T11:00:00.000Z",
  },
  {
    id: "blade-runner",
    title: "Blade Runner",
    year: 1982,
    genres: ["Sci-Fi", "Drama"],
    director: "Ridley Scott",
    runtime: 117,
    coverUrl: "",
    atlasIndex: 2,
    shelfId: "sci-fi",
    notes: "Final Cut.",
    review: "Rain, neon, memory, and a city that feels exhausted.",
    rating: 5,
    label: "Do Not Tape Over",
    watchedDates: ["2026-05-17"],
    rentalDate: "2026-05-15",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-05-11T18:20:00.000Z",
  },
  {
    id: "the-thing",
    title: "The Thing",
    year: 1982,
    genres: ["Horror", "Sci-Fi"],
    director: "John Carpenter",
    runtime: 109,
    coverUrl: "",
    atlasIndex: 3,
    shelfId: "horror",
    notes: "Best with the lights off.",
    review: "Paranoia that gets colder every minute.",
    rating: 5,
    label: "Be Kind Rewind",
    watchedDates: ["2025-12-19"],
    rentalDate: "2025-12-18",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-04-22T09:00:00.000Z",
  },
  {
    id: "jurassic-park",
    title: "Jurassic Park",
    year: 1993,
    genres: ["Adventure", "Sci-Fi"],
    director: "Steven Spielberg",
    runtime: 127,
    coverUrl: "",
    atlasIndex: 4,
    shelfId: "weekend",
    notes: "Keep this one near the front counter.",
    review: "Wonder and danger in equal measure.",
    rating: 5,
    label: "Staff Pick",
    watchedDates: ["2026-07-12"],
    rentalDate: "2026-07-11",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-07-10T16:45:00.000Z",
  },
  {
    id: "ghostbusters",
    title: "Ghostbusters",
    year: 1984,
    genres: ["Comedy", "Fantasy"],
    director: "Ivan Reitman",
    runtime: 105,
    coverUrl: "",
    atlasIndex: 5,
    shelfId: "comedy",
    notes: "Late-fee forgiven.",
    review: "A workplace comedy with proton packs.",
    rating: 4,
    label: "Late Return",
    watchedDates: ["2026-03-14"],
    rentalDate: "2026-03-11",
    rewound: true,
    favorite: false,
    watchNext: false,
    returned: false,
    dateAdded: "2026-03-09T12:00:00.000Z",
  },
  {
    id: "princess-bride",
    title: "The Princess Bride",
    year: 1987,
    genres: ["Adventure", "Comedy", "Fantasy"],
    director: "Rob Reiner",
    runtime: 98,
    coverUrl: "",
    atlasIndex: 6,
    shelfId: "staff-picks",
    notes: "Membership-card favorite.",
    review: "Warm, funny, and endlessly quotable.",
    rating: 5,
    label: "Staff Pick",
    watchedDates: ["2026-02-14"],
    rentalDate: "2026-02-13",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-02-02T10:25:00.000Z",
  },
  {
    id: "terminator-2",
    title: "Terminator 2",
    year: 1991,
    genres: ["Action", "Sci-Fi"],
    director: "James Cameron",
    runtime: 137,
    coverUrl: "",
    atlasIndex: 7,
    shelfId: "action",
    notes: "Two-tape energy in one case.",
    review: "Huge action with an unexpectedly human center.",
    rating: 5,
    label: "Do Not Tape Over",
    watchedDates: ["2026-01-23"],
    rentalDate: "2026-01-22",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2026-01-10T20:00:00.000Z",
  },
  {
    id: "the-shining",
    title: "The Shining",
    year: 1980,
    genres: ["Horror", "Drama"],
    director: "Stanley Kubrick",
    runtime: 146,
    coverUrl: "",
    atlasIndex: 8,
    shelfId: "horror",
    notes: "Winter rental.",
    review: "The hallways are scarier than the ghosts.",
    rating: 5,
    label: "Cult Classic",
    watchedDates: ["2025-10-30"],
    rentalDate: "2025-10-28",
    rewound: false,
    favorite: false,
    watchNext: false,
    returned: false,
    dateAdded: "2025-10-20T13:00:00.000Z",
  },
  {
    id: "groundhog-day",
    title: "Groundhog Day",
    year: 1993,
    genres: ["Comedy", "Fantasy"],
    director: "Harold Ramis",
    runtime: 101,
    coverUrl: "",
    atlasIndex: 9,
    shelfId: "comedy",
    notes: "Repeat rental, naturally.",
    review: "Gets wiser every time around.",
    rating: 4,
    label: "Be Kind Rewind",
    watchedDates: ["2026-02-02", "2025-02-02"],
    rentalDate: "2026-02-01",
    rewound: true,
    favorite: true,
    watchNext: false,
    returned: false,
    dateAdded: "2025-09-02T08:40:00.000Z",
  },
  {
    id: "akira",
    title: "Akira",
    year: 1988,
    genres: ["Animation", "Sci-Fi"],
    director: "Katsuhiro Otomo",
    runtime: 124,
    coverUrl: "",
    atlasIndex: 10,
    shelfId: "sci-fi",
    notes: "Imported tape behind the counter.",
    review: "A city in motion, then detonation.",
    rating: 5,
    label: "Cult Classic",
    watchedDates: [],
    rentalDate: "2026-07-19",
    rewound: false,
    favorite: true,
    watchNext: true,
    returned: false,
    dateAdded: "2026-07-19T19:10:00.000Z",
  },
  {
    id: "raiders",
    title: "Raiders of the Lost Ark",
    year: 1981,
    genres: ["Adventure", "Action"],
    director: "Steven Spielberg",
    runtime: 115,
    coverUrl: "",
    atlasIndex: 11,
    shelfId: "action",
    notes: "Saturday matinee pick.",
    review: "A serial adventure that never stops moving.",
    rating: 5,
    label: "Staff Pick",
    watchedDates: [],
    rentalDate: "2026-07-22",
    rewound: false,
    favorite: false,
    watchNext: true,
    returned: false,
    dateAdded: "2026-07-22T17:30:00.000Z",
  },
];

export function createDefaultState(): LibraryState {
  return {
    movies: sampleMovies,
    shelves: defaultShelves,
    theme: "classic",
    view: "shelf",
    sort: "title",
    activeCollection: "all",
    activeShelfId: "all",
    search: "",
    filters: {
      genre: "all",
      rating: 0,
      watched: "all",
      rewound: "all",
    },
    onboardingDismissed: false,
    clientUpdatedAt: Date.now(),
  };
}
