export type HistoryItem = { id: string; date: string; type: string; note: string };
export type Contact = {
  id: string; firstName: string; lastName: string; pronouns: string; title: string; company: string;
  email: string; phone: string; address: string; website: string; birthday: string; category: string;
  tags: string[]; notes: string; preferred: string; image: string; favorite: boolean; archived: boolean;
  followUp: string; reminder: string; history: HistoryItem[]; createdAt: string;
};
export type Group = { id: string; name: string };
const d = (offset: number) => { const date = new Date(); date.setDate(date.getDate() + offset); return date.toISOString().slice(0, 10); };
export const defaultGroups: Group[] = ["Personal", "Work", "Family", "Clients", "Friends"].map((name) => ({ id: name.toLowerCase(), name }));
export const sampleContacts: Contact[] = [
  { id: "maya-chen", firstName: "Maya", lastName: "Chen", pronouns: "she/her", title: "Creative Director", company: "Northstar Studio", email: "maya.chen@example.com", phone: "(312) 555-0142", address: "1842 W. Addison St., Chicago, IL", website: "https://northstar.example.com", birthday: "1988-04-19", category: "Work", tags: ["design", "client"], notes: "Ask about the spring identity project.", preferred: "Email", image: "", favorite: true, archived: false, followUp: d(3), reminder: "Send the revised moodboard.", history: [{ id: "h1", date: d(-8), type: "Meeting", note: "Reviewed the first direction." }], createdAt: d(-40) },
  { id: "daniel-brooks", firstName: "Daniel", lastName: "Brooks", pronouns: "he/him", title: "Independent Software Developer", company: "", email: "daniel.brooks@example.com", phone: "(773) 555-0188", address: "", website: "https://daniel.example.com", birthday: "1990-09-02", category: "Friends", tags: ["developer", "coffee"], notes: "Knows a good mechanical keyboard shop.", preferred: "Phone", image: "", favorite: false, archived: false, followUp: "", reminder: "", history: [{ id: "h2", date: d(-22), type: "Lunch", note: "Talked about small desktop tools." }], createdAt: d(-32) },
  { id: "elena-rodriguez", firstName: "Elena", lastName: "Rodriguez", pronouns: "she/her", title: "Editor", company: "Paper Trail Press", email: "elena.rodriguez@example.com", phone: "(312) 555-0110", address: "72 N. Morgan St., Chicago, IL", website: "", birthday: "1985-11-14", category: "Work", tags: ["editor", "books"], notes: "Interested in the next manuscript.", preferred: "Email", image: "", favorite: true, archived: false, followUp: d(-2), reminder: "Overdue: share chapter outline.", history: [], createdAt: d(-20) },
  { id: "marcus-lee", firstName: "Marcus", lastName: "Lee", pronouns: "they/them", title: "Product Designer", company: "Signal Works", email: "marcus.lee@example.com", phone: "(847) 555-0161", address: "", website: "https://signal.example.com", birthday: "1991-06-08", category: "Clients", tags: ["product", "ux"], notes: "Prefers async updates.", preferred: "Email", image: "", favorite: false, archived: false, followUp: d(10), reminder: "Check in on the prototype.", history: [], createdAt: d(-14) },
  { id: "sophie-martin", firstName: "Sophie", lastName: "Martin", pronouns: "she/her", title: "Photographer", company: "", email: "sophie.martin@example.com", phone: "(773) 555-0135", address: "", website: "", birthday: "1987-02-26", category: "Friends", tags: ["photo"], notes: "Send the gallery link.", preferred: "Text", image: "", favorite: false, archived: false, followUp: "", reminder: "", history: [], createdAt: d(-10) },
  { id: "jordan-williams", firstName: "Jordan", lastName: "Williams", pronouns: "he/him", title: "Accountant", company: "Williams & Co.", email: "jordan.williams@example.com", phone: "(312) 555-0197", address: "", website: "", birthday: "1982-12-10", category: "Work", tags: ["finance"], notes: "Annual paperwork contact.", preferred: "Phone", image: "", favorite: false, archived: false, followUp: "", reminder: "", history: [], createdAt: d(-7) },
  { id: "priya-shah", firstName: "Priya", lastName: "Shah", pronouns: "she/her", title: "Marketing Consultant", company: "Brightline", email: "priya.shah@example.com", phone: "(630) 555-0104", address: "", website: "", birthday: "1989-07-21", category: "Clients", tags: ["marketing", "strategy"], notes: "Great at launch plans.", preferred: "Email", image: "", favorite: true, archived: false, followUp: "", reminder: "", history: [], createdAt: d(-5) },
  { id: "thomas-reed", firstName: "Thomas", lastName: "Reed", pronouns: "he/him", title: "Bookstore Owner", company: "Reed & Sons Books", email: "thomas.reed@example.com", phone: "(773) 555-0174", address: "", website: "", birthday: "1978-03-03", category: "Personal", tags: ["books", "local"], notes: "Ask about the used reference section.", preferred: "Email", image: "", favorite: false, archived: false, followUp: "", reminder: "", history: [], createdAt: d(-3) },
];
